export const DEFAULT_SETTINGS = {
  KEEPMIND_MODEL: 'claude-sonnet-4-6',
  KEEPMIND_CONTEXT_OBSERVATIONS: '50',
  KEEPMIND_WORKER_PORT: '37777',
  KEEPMIND_WORKER_HOST: '127.0.0.1',

  KEEPMIND_PROVIDER: 'claude',
  KEEPMIND_GEMINI_API_KEY: '',
  KEEPMIND_GEMINI_MODEL: 'gemini-2.5-flash-lite',
  KEEPMIND_OPENROUTER_API_KEY: '',
  KEEPMIND_OPENROUTER_MODEL: 'xiaomi/mimo-v2-flash:free',
  KEEPMIND_OPENROUTER_SITE_URL: '',
  KEEPMIND_OPENROUTER_APP_NAME: 'keepmind',
  KEEPMIND_GEMINI_RATE_LIMITING_ENABLED: 'true',

  KEEPMIND_CONTEXT_SHOW_READ_TOKENS: 'false',
  KEEPMIND_CONTEXT_SHOW_WORK_TOKENS: 'false',
  KEEPMIND_CONTEXT_SHOW_SAVINGS_AMOUNT: 'false',
  KEEPMIND_CONTEXT_SHOW_SAVINGS_PERCENT: 'true',

  KEEPMIND_CONTEXT_FULL_COUNT: '0',
  KEEPMIND_CONTEXT_FULL_FIELD: 'narrative',
  KEEPMIND_CONTEXT_SESSION_COUNT: '10',

  KEEPMIND_CONTEXT_SHOW_LAST_SUMMARY: 'true',
  KEEPMIND_CONTEXT_SHOW_LAST_MESSAGE: 'false',

  KEEPMIND_EXCLUDED_PROJECTS: '',
  KEEPMIND_FOLDER_MD_EXCLUDE: '[]',
} as const;
