import { describe, it, expect } from 'bun:test';
import {
  deterministicFieldsForToolUse,
  deterministicFieldsForBatch,
} from '../../src/sdk/deterministic-fields.js';
import { buildObserverSystemPrompt } from '../../src/sdk/prompts.js';

/**
 * ACCEPTANCE TEST 4 — file, tool and time fields come from the hook payload and
 * are never generated by the model.
 */
describe('deterministic fields (acceptance test 4)', () => {
  it('attributes a Read to files_read', () => {
    const fields = deterministicFieldsForToolUse('Read', { file_path: 'src/index.ts' });
    expect(fields.files_read).toEqual(['src/index.ts']);
    expect(fields.files_modified).toEqual([]);
  });

  it('attributes a Write/Edit to files_modified', () => {
    expect(deterministicFieldsForToolUse('Write', { file_path: 'src/a.ts' }).files_modified).toEqual(['src/a.ts']);
    expect(deterministicFieldsForToolUse('Edit', { file_path: 'src/b.ts' }).files_modified).toEqual(['src/b.ts']);
  });

  it('normalises Windows separators so the same file compares equal', () => {
    const fields = deterministicFieldsForToolUse('Read', { file_path: 'C:\\repo\\src\\index.ts' });
    expect(fields.files_read).toEqual(['C:/repo/src/index.ts']);
  });

  it('collects MultiEdit batches from edits[]', () => {
    const fields = deterministicFieldsForToolUse('MultiEdit', {
      edits: [{ file_path: 'a.ts' }, { file_path: 'b.ts' }],
    });
    expect(fields.files_modified.sort()).toEqual(['a.ts', 'b.ts']);
  });

  it('claims nothing for tools that are neither readers nor writers', () => {
    // A Bash argument that happens to look like a path is not a read.
    const fields = deterministicFieldsForToolUse('Bash', { command: 'cat src/index.ts', path: 'src/index.ts' });
    expect(fields.files_read).toEqual([]);
    expect(fields.files_modified).toEqual([]);
  });

  it('merges a batch, with modification winning over read', () => {
    const fields = deterministicFieldsForBatch([
      { tool_name: 'Read', tool_input: { file_path: 'src/a.ts' } },
      { tool_name: 'Read', tool_input: { file_path: 'src/b.ts' } },
      { tool_name: 'Edit', tool_input: { file_path: 'src/a.ts' } },
    ]);
    expect(fields.files_modified).toEqual(['src/a.ts']);
    expect(fields.files_read).toEqual(['src/b.ts']);
  });

  it('matches the hook payload exactly for a realistic batch', () => {
    const hookPayload = [
      { tool_name: 'Read', tool_input: { file_path: '/repo/src/worker/ClaudeProvider.ts' } },
      { tool_name: 'Edit', tool_input: { file_path: '/repo/src/sdk/prompts.ts' } },
      { tool_name: 'Bash', tool_input: { command: 'npm run build' } },
    ];
    const fields = deterministicFieldsForBatch(hookPayload);
    expect(fields.files_read).toEqual(['/repo/src/worker/ClaudeProvider.ts']);
    expect(fields.files_modified).toEqual(['/repo/src/sdk/prompts.ts']);
  });

  it('no longer asks the model for those fields', () => {
    const mode = {
      observation_types: [{ id: 'discovery' }],
      prompts: {
        system_identity: 'i', observer_role: 'r', spatial_awareness: 's',
        recording_focus: 'f', skip_guidance: 'g', output_format_header: 'h',
        type_guidance: 't', xml_title_placeholder: '', xml_subtitle_placeholder: '',
        xml_fact_placeholder: '', field_guidance: '', xml_narrative_placeholder: '',
        xml_concept_placeholder: '', concept_guidance: '', xml_file_placeholder: '',
        format_examples: '', footer: '',
      },
    } as any;
    const prompt = buildObserverSystemPrompt(mode);
    // Check the OUTPUT SCHEMA, not the whole prompt: the instruction that
    // forbids these elements necessarily names them. What must be gone is their
    // presence in the template the model fills in — that is what turned them
    // into a per-observation output-token cost.
    const schema = prompt.slice(prompt.indexOf('<observation>'), prompt.indexOf('</observation>'));
    expect(schema).not.toContain('files_read');
    expect(schema).not.toContain('files_modified');
    expect(schema).toContain('<narrative>');
    expect(prompt).toContain('Do NOT emit');
  });
});
