// SPDX-License-Identifier: Apache-2.0
//
// Fields the model must never be asked to produce.
//
// `files_read` and `files_modified` were generated by the observer LLM, which
// then had to copy them back out of a `<parameters>` block that had *already*
// been truncated to fit the context window. That is expensive (they are part of
// the output token count on every single observation), unreliable (a truncated
// parameters block yields invented or missing paths), and unnecessary: the hook
// payload contains the exact path, the exact tool name and the exact timestamp.
//
// Deriving them here makes them correct by construction and lets the prompt drop
// two array fields from its output schema. `tests/sdk/deterministic-fields.test.ts`
// asserts they match the hook data (acceptance test 4).

import { logger } from '../utils/logger.js';

/** Tools that only read; their file_path is evidence of a read. */
const READ_TOOLS = new Set(['Read', 'NotebookRead', 'ReadFile']);

/** Tools that write; their file_path is evidence of a modification. */
const WRITE_TOOLS = new Set(['Edit', 'MultiEdit', 'Write', 'NotebookEdit', 'ApplyPatch']);

const PATH_KEYS = ['file_path', 'filePath', 'path', 'notebook_path', 'target_file'];

export interface DeterministicFields {
  files_read: string[];
  files_modified: string[];
}

function collectPaths(toolInput: unknown): string[] {
  if (!toolInput || typeof toolInput !== 'object' || Array.isArray(toolInput)) return [];
  const record = toolInput as Record<string, unknown>;
  const out: string[] = [];
  for (const key of PATH_KEYS) {
    const value = record[key];
    if (typeof value === 'string' && value.length > 0) out.push(value);
  }
  const list = record.filePaths;
  if (Array.isArray(list)) {
    for (const entry of list) {
      if (typeof entry === 'string' && entry.length > 0) out.push(entry);
    }
  }
  // MultiEdit-style batches: edits[].file_path
  const edits = record.edits;
  if (Array.isArray(edits)) {
    for (const edit of edits) {
      if (edit && typeof edit === 'object' && !Array.isArray(edit)) {
        const p = (edit as Record<string, unknown>).file_path;
        if (typeof p === 'string' && p.length > 0) out.push(p);
      }
    }
  }
  return out;
}

/** Normalise to forward slashes so the same file compares equal across hosts. */
function normalise(p: string): string {
  return p.replace(/\\/g, '/');
}

/**
 * Derive the file lists for ONE tool use. A tool that is neither a known reader
 * nor a known writer contributes nothing: guessing from a path alone would
 * attribute a Bash command's argument as a read.
 */
export function deterministicFieldsForToolUse(
  toolName: string | undefined,
  toolInput: unknown
): DeterministicFields {
  const empty: DeterministicFields = { files_read: [], files_modified: [] };
  if (!toolName) return empty;
  const paths = collectPaths(toolInput).map(normalise);
  if (paths.length === 0) {
    // A known reader/writer with no extractable path means the tool's input
    // shape changed (a new key, a renamed field). Silently it just yields an
    // observation with empty file lists, and the file timeline quietly stops
    // covering that tool — worth a line in the log rather than a mystery later.
    if (WRITE_TOOLS.has(toolName) || READ_TOOLS.has(toolName)) {
      logger.debug('SDK', 'File-bearing tool produced no extractable path', {
        toolName,
        inputKeys: toolInput && typeof toolInput === 'object'
          ? Object.keys(toolInput as Record<string, unknown>).join(',')
          : typeof toolInput,
      });
    }
    return empty;
  }
  if (WRITE_TOOLS.has(toolName)) return { files_read: [], files_modified: paths };
  if (READ_TOOLS.has(toolName)) return { files_read: paths, files_modified: [] };
  return empty;
}

/**
 * Merge the fields for a whole coalesced batch. A file that was both read and
 * modified counts only as modified — the stronger claim, and what the file
 * timeline wants to surface.
 */
export function deterministicFieldsForBatch(
  uses: Array<{ tool_name?: string; tool_input?: unknown }>
): DeterministicFields {
  const read = new Set<string>();
  const modified = new Set<string>();
  for (const use of uses) {
    const fields = deterministicFieldsForToolUse(use.tool_name, use.tool_input);
    for (const p of fields.files_read) read.add(p);
    for (const p of fields.files_modified) modified.add(p);
  }
  for (const p of modified) read.delete(p);
  return { files_read: [...read], files_modified: [...modified] };
}
